### ISSUE TITLE
gmailctl and Google Advanced Protection

### ISSUE THREAD

**Issue by palcu** [mbrt/gmailctl#111]
Hello,

I recently tried setting up this for my personal Gmail account, but [Google Advanced Protection](https://landing.google.com/advancedprotection/) stopped me from doing it:

> Google cannot give this app access to your account data because Advanced Protection is turned on for your Google Account.

It's probably impossible for me to use the API, since my app cannot get whitelisted.

However, I was wondering if there would be a `--local` flag that could point to a config on the machine. I don't mind pressing the export and import buttons once in a while when I need to do changes.

palcu@

**Comment by mbrt** [comment]
Ah, I certainly should investigate how to tackle Google Advanced Protection. It seems weird to me that you can't have access to APIs for your own account.

In the meantime, I suggest you to use `gmailctl export` and manually import the filters through the Gmail UI.
