### ISSUE TITLE
Forwarding action isn't being applied

### ISSUE THREAD

**Issue by DannyDeLoach** [mbrt/gmailctl#117]
When I include the 'forward' action in a filter, the action is not created in Gmail. Here is my code in the config.jsonnet file:

```jsonnet
  local groupDelete = [
    '<redacted>@outlook.com',
  ];
  // ...
  {
    filter: fromGroup(groupDelete),
    actions: {
      forward: '<redacted>@gmail.com',
      labels: ["AutomaticallyDeleted"],
      delete: true,
    }
  },
```

Before applying the config, I used the 'diff' command. Here is the result:

```
Filters:
--- Current
+++ TO BE APPLIED
@@ -1 +1,6 @@
+* Criteria:
+    from: <redacted>@outlook.com
+  Actions:
+    delete
+    apply label: AutomaticallyDeleted
```

Note the forwarding action isn't listed.

When I apply the config to Gmail, this is what the resulting filter looks like:
![image](https://user-images.githubusercontent.com/24360823/80989801-6d6b0e00-8e03-11ea-8f5d-f1cbde0eb068.png)

I tried manually adding a forwarding action to the filter myself from within Gmail settings, and it worked as expected.

I also created new gmail api credentials for gmailctl. The same problem persists.

Is there something else I need to do, in order to get the forward action to apply? Thanks.

**Comment by mbrt** [comment]
Are you sure you're using the latest version of gmailctl? Another possibility is that your config is somewhat wrong. Could you make it minimal in order to test this case?

I tried to reproduce your problem locally, but it works for me:

```
$ gmailctl diff -f cfg2.jsonnet
Filters:
--- Current
+++ TO BE APPLIED
@@ -1 +1,7 @@
+* Criteria:
+    from: foobarbazfaz
+  Actions:
+    delete
+    apply label: Somelabel
+    forward to: something@outlook.com
```

**Comment by DannyDeLoach** [comment]
It's working now. I think the issue was I had not properly updated gmailctl. I thought I had updated it, but apparently it wasn't updated.

Previously I saw this, when I applied filters:
`Filters:
--- Current
+++ TO BE APPLIED
@@ -1 +1,6 @@`

Now, I see this:
`Filters:
--- Current
+++ TO BE APPLIED
@@ -1 +1,7 @@`

I assume that means I have now updated from version 1.6 to 1.7. Is that right?

Thanks very much for your help with this.

**Comment by mbrt** [comment]
Unfortunately there's no way to tell the version of gmailctl yet. Ideally I should add a `version` command, so this becomes more clear.

No, that's only part of the diff format. The numbers within `@@` are the line numbers to which the next diff chunk refers to (see https://unix.stackexchange.com/a/480542/181715). You can pretty much ignore those, since the "input files" are generated from the config and the current Gmail configuration, so you can't see them directly.
