### ISSUE TITLE
Add version subcommand

### ISSUE THREAD

**Issue by mbrt** [mbrt/gmailctl#120]
From a gmailctl binary it's not easy to tell which version it was compiled from. We need to add a `version` subcommand and implement some kind of automatic versioning.

**Comment by srinidhis94** [comment]
This can be done either at build time using ldflags and passing args and have a build script or makefile or having a verison file such as this.
https://github.com/gohugoio/hugo/blob/5f621df2570236a08cd21e8dd1c60502ec3db328/common/hugo/version_current.go
https://github.com/gohugoio/hugo/blob/master/commands/version.go
What would you prefer?

**Comment by mbrt** [comment]
I would prefer to keep the regular `go build` flow untouched, so a version file is better. The only problem is that there needs to be some automation for updating the version file, otherwise I'll invariably forget.

**Comment by srinidhis94** [comment]
If you would keep it as a habit to first create a git tag, then build the binary, we can find latest tag you have created using following command.
git describe --tags `git rev-list --tags --max-count=1`
It can then be used to assign version.

**Comment by mbrt** [comment]
Yes, but I have to remember doing this every time I create a tag. I'm sure I'm going to forget, so my current thinking is that I'm going to hold off any implementation until there's an easy semi-automated way to do the release.

Perhaps it's just as easy as creating a script for myself.

**Comment by srinidhis94** [comment]
I was thinking a makefile such as this would make things easier. I know it's not what you had in mind but it solves  the problem. You might have something similar. But since I didn't find anything similar in repo, making a suggestion.



```
SHELL := /bin/bash
GOBIN = ${GOPATH}/bin
GO111MODULE=auto
IMPORT_PATH = github.com/mbrt/gmailctl/cmd/gmailctl/cmd
DATE = $(shell date -u '+%Y-%m-%d_%I:%M:%S%p')
COMMIT = $(shell git rev-parse HEAD)
TAG = $(shell git describe --tags `git rev-list --tags --max-count=1`)
VERSION = $(shell echo ${TAG} | egrep -o '[0-9]+\.[0-9a-z.\-]+')
LD_FLAGS = -ldflags "-X ${IMPORT_PATH}.BuildTime=${DATE} -X ${IMPORT_PATH}.GitHash=${COMMIT} -X ${IMPORT_PATH}.Version=${TAG}"

all : vet build

vet:
	@go vet ./...

build:
	@go mod vendor
	@for platform in darwin linux windows; do \
		if [ $$platform == windows ]; then extension=.exe; fi; \
		GOOS=${platform} GOARCH=amd64 go build -mod=vendor -v ${LD_FLAGS} -a -o release/gmail_ctl-${VERSION}-$$platform-amd64$$extension; \
  	done
	@GOOS=linux GOARCH=arm64 go build -mod=vendor -v ${LD_FLAGS} -a -o release/gmail_ctl-linux-arm64

staticcheck:
	@go get -u "honnef.co/go/tools/cmd/staticcheck"
	go run honnef.co/go/tools/cmd/staticcheck -- $$(go list ./...)
```

**Comment by mbrt** [comment]
Something like https://github.com/MylesBorins/node-osc/blob/main/.github/workflows/bump-version.yml might help I think. A GH action that updates the version file and creates the git tag.

I still have a very manual process of creating new releases today, and I think this might help, along with the new "Autogenerate release notes" functionality.
