### ISSUE TITLE
Filter color fails if it the color is uppercased

### ISSUE THREAD

**Issue by hjemmel** [mbrt/gmailctl#130]
When I added color like `#41236D` that is supported by [Gmail API](https://developers.google.com/gmail/api/v1/reference/users/labels#resource) I get the following error:

`Error: creating labels: creating label "AppSignal/Kickback": googleapi: Error 400: Label color #41236D is not on the allowed color palette, invalidArgument`

If I do the same with the but lowercasing the color, the `gmailctl apply` command works perfectly.

Maybe it would be a good idea to lowercase the colors before send them to the API

**Comment by mbrt** [comment]
Gmail APIs accept only lowercase hex strings and I'm reluctant to relax the restrictions, unless there's a good reason. This is to avoid confusion and potential incompatibilities in the case Gmail changes something.

What I can do however is returning a better error message. You found the docs by yourself but it's not necessarily obvious to everyone, so I'm going to go ahead and do that.
