### ISSUE TITLE
Regular Expressions in subject

### ISSUE THREAD

**Issue by gauntface** [mbrt/gmailctl#135]
Is it possible to use regular expression (ish) syntax in subject filters?

For example, `subject:\d* (` works in gmail, however adding this to my `jsonnet` file I get the following error:

```
Error: syntax error in config file: parsing jsonnet: config.jsonnet:347:24-34 Unknown escape sequence in string literal: \d
```

I can write this as `subject: "\\d* ("` so that tests can run, but tests don't match the content.

Is there anything else I could try or is this just not supported?

**Comment by gauntface** [comment]
Ignore me, I'm pretty sure I was misunderstanding what gmail was doing.

**Comment by mbrt** [comment]
Yeah, regular expressions are not supported in Gmail filters, so this shouldn't work.

On a side note, `"\d*"` is escaped in jsonnet (just like it would in C). If you need verbatim strings you can use `@'\d*'`. See the [tutorial](https://jsonnet.org/learning/tutorial.html).
