### ISSUE TITLE
"Other" is no longer one of the available options for "Application Type"

### ISSUE THREAD

**Issue by skyzyx** [mbrt/gmailctl#157]
> 6c. Select 'Other' as 'Application type' and give it a name.

"Other" is no longer one of the available options for "Application Type". Is there an alternative we should choose?

<img width="583" alt="Screen Shot 2020-12-26 at 2 14 32 PM" src="https://user-images.githubusercontent.com/39447/103159978-be5db700-4784-11eb-859e-2769dee4cbb8.png">

**Comment by skyzyx** [comment]
Using "TVs and Limited Input Devices" appears to work.

**Comment by mbrt** [comment]
Interesting. I feel like the best option is "Desktop app" now. I'll update the docs accordingly.
