### ISSUE TITLE
Allow to have config in multiple files

### ISSUE THREAD

**Issue by qqgg231** [mbrt/gmailctl#178]
My situation: 

I need to apply filters to multiple gmail accounts:

account1
account2
account3

I would like to have some rules shared and some rules not shared:

rules for account1: 
```
account1_config.jsonnet
shared_config.jsonnet
```

rules for account2: 
```
account2_config.jsonnet
shared_config.jsonnet
```

rules for account3: 
```
account3_config.jsonnet
shared_config.jsonnet
```

How to achieve it, so I can have some rules in one file and some in second file? (or even in more files)

**Comment by mbrt** [comment]
Please see https://github.com/mbrt/gmailctl#multiple-gmail-accounts.
