### ISSUE TITLE
'download' doesn't support UTF-8 characters / emojis

### ISSUE THREAD

**Issue by qqgg231** [mbrt/gmailctl#179]
For example:

`ąż 🟡` in label name gives:

`─ů┼╝ ­ččí`

Then it is not possible to apply such rules:

`Error: syntax error in config file: parsing jsonnet: config.jsonnet:1:1 Could not lex the character '\ufffd'`

The same happens if rules contains such characters.

**Comment by mbrt** [comment]
Could you post a minimal config that reproduce the problem here?

**Comment by qqgg231** [comment]
```
{
  version: "v1alpha3",
  author: {
    name: "YOUR NAME HERE (auto imported)",
    email: "your-email@gmail.com"
  },
  labels: [
    {
      name: "Test label",
    },
  ],
  rules: [
  ]
}

```
While trying to do this, I saw that cause of issue is different than I thought initially:

It is because download file has UTF-16 LE ecnoding instead of UTF-8. Characters and emojis doesn't matter.

How to reproduce: 
In Powershell on Windows10 I type:
` gmailctl download --config=. >download12345.jsonnet`
and it generates download12345.jsonnet with UTF-16 LE encoding

![2021-04-27 23_14_13-faktury ścieżka - OneNote](https://user-images.githubusercontent.com/11590960/116314141-04686d00-a7af-11eb-86dd-720a965b693f.png)

When I convert this file to UTF-8 it works ok.

----

Multiple solutions to this problem: 
https://stackoverflow.com/questions/5596982/using-powershell-to-write-a-file-in-utf-8-without-the-bom

**Comment by qqgg231** [comment]
Also this may help:

https://stackoverflow.com/questions/68062063/how-to-save-to-file-non-ascii-output-of-program-in-powershell/68064432#68064432
