### ISSUE TITLE
Apply rules to existing emails

### ISSUE THREAD

**Issue by super-cache-money** [mbrt/gmailctl#180]
The gmail interface gives you the ability to do this:
![image](https://user-images.githubusercontent.com/1463145/116543568-4fd56500-a8ee-11eb-8f44-6f6cd27f51f8.png)
This tool being unable to do so (AFAICT), has made me stop using it - as much as I love the idea :(

**Comment by mbrt** [comment]
Please see https://github.com/mbrt/gmailctl#known-issues. This is by design.
