### ISSUE TITLE
Get `diff` in json/jsonnet format

### ISSUE THREAD

**Issue by karolzlot** [mbrt/gmailctl#186]
Idea:

Add command switch to diff command so it generates json / jsonnet output.

It should generate separately items removed and items added.

I am more interested in situation where if I use Gmail Web UI to add filter then I can easily add it to config later by copy paste from diff-json to config.jsonnet

But seeing separately removed filters in json/jsonnet also won't hurt.

Please also suggest alternative solutions!

**Comment by mbrt** [comment]
The local filters are mingled quite a bit before comparing them to the remote ones (i.e. the ones coming from the Gmail UI). Because of that I'm not sure things will be very useful in a JSON / Jsonnet output.

Would using `gmailctl download` help? You'd just have to find the new filter in the output.

**Comment by karolzlot** [comment]
@mbrt 
I tried to make my own tool based on `gmailctl download`, but it works only with simple filters. If I have filters in jsonnet which for example use `or:` then I get way more differences than really present.

> The local filters are mingled quite a bit before comparing them to the remote ones (i.e. the ones coming from the Gmail UI). Because of that I'm not sure things will be very useful in a JSON / Jsonnet output.

It is exactly why it would be very useful. 
Current `diff` command gives precisely the output I need except it's output format, I would prefer to have option to get JSON.

**Comment by mbrt** [comment]
`gmailctl` is intended for users that manage their filters through it, and not through the Gmail UI. I'm reluctant in adding any features that go beyond this simple use case, as any feature is ultimately a liability. I have very limited time to dedicate to the maintenance of this tool and I want to avoid scope creep.
