### ISSUE TITLE
Can I safely have duplicates in config.jsonnet?

### ISSUE THREAD

**Issue by karolzlot** [mbrt/gmailctl#188]
I see that probably gmailctl checks for duplicates and won't export two the same filters / labels to gmail:

https://github.com/mbrt/gmailctl/commit/48fdf5886deddf4b233ef2373a0b48e8f6866dc5

Please confirm, because I can't find it in docs.

I see in code that filters are removed, but what about duplicate labels?

**Comment by karolzlot** [comment]
Ok, I see that duplicate labels are not checked, I see them when I run `diff`.

**Comment by mbrt** [comment]
Yes, I think there's no check for duplicated labels. Why? Is that a problem?

**Comment by karolzlot** [comment]
I am not sure if gmail will just ignore them? 

Because if yes then `diff` output shouldn't show them probably. 

But after thinking about it, for my use case it probably won't matter.
