### ISSUE TITLE
Feature Request: Apply label to matching 

### ISSUE THREAD

**Issue by peteroneilljr** [mbrt/gmailctl#196]
Looks like it doesn't exist in the Gmail API yet. But once it's added, it would be nice to have a flag in gmailctl to `--apply-filters-to-matching`

It the GUI it is shown as: `Also apply filter to matching conversations.`

Link to open gmail api: [feature request](https://issuetracker.google.com/issues/62715881)

**Comment by mbrt** [comment]
This is a known limitation of gmailctl. The permissions required for this require full access to your inbox, which has the potential to wipe out all your emails (in case something goes wrong). See https://github.com/mbrt/gmailctl#known-issues for a workaround.
