### ISSUE TITLE
Why can’t `markSpam` == true?

### ISSUE THREAD

**Issue by skyzyx** [mbrt/gmailctl#216]
The software yells at me when I try to set `markSpam: true`. I was just wondering if there's a reason and/or any way around it.

I'm also assuming this is a common issue that people know about. If it isn't, I'm happy to provide more information (as this is definitely not a complete bug report).

**Comment by mbrt** [comment]
This is not an accident. Gmail doesn't allow marking something as spam directly from filters, so this is not something gmailctl can do something about.

I know it's not the same, but one way to clear off some unwanted emails would be to delete them or "mark as read and archive".

**Comment by skyzyx** [comment]
Makes sense.

I guess my next question is: Why is this even an available option? (Not sure where I copy-pasted it from, but it was almost definitely from somewhere in this project and its docs.)

**Comment by mbrt** [comment]
I don't see any trace of `markSpam: true` anywhere in the repo (https://sourcegraph.com/search?patternType=literal&q=repo%3Ambrt%2Fgmailctl%20markSpam%3A).

You can set it to `false` however. From the README:

> `markSpam: false`: do never mark these messages as spam. Note that setting this field to true is not supported by Gmail.

**Comment by gtback** [comment]
Thanks, @mbrt (and thanks for the amazing tool, by the way!)

This matches what I would expect, given the GMail Filter UI:

![image](https://user-images.githubusercontent.com/1045796/144455007-c183072c-7542-45ae-b238-3075c1e66f0e.png)

You can specify a filter to *not* mark a message a spam, but not the opposite.

**Comment by mbrt** [comment]
Yup!
