### ISSUE TITLE
Support for templates ("cannedResponse") action

### ISSUE THREAD

**Issue by bkudria** [mbrt/gmailctl#226]
GMail has support for sending a templated response. It would be nice to support this in gmailctl!

<details>
<summary>Here's an example filter I exported that shows this</summary>

```
<?xml version='1.0' encoding='UTF-8'?>
<feed xmlns='http://www.w3.org/2005/Atom' xmlns:apps='http://schemas.google.com/apps/2006'>
	<title>Mail Filters</title>
	<id>tag:mail.google.com,2008:filters:z0000001642000000000*5567497000000000734</id>
	<updated>2022-01-21T20:44:27Z</updated>
	<author>
		<name>Benjamin Kudria</name>
		<email>ben@kudria.net</email>
	</author>
	<entry>
		<category term='filter'></category>
		<title>Mail Filter</title>
		<id>tag:mail.google.com,2008:filters:z0000001642000000000*5567497000000000734</id>
		<updated>2022-01-21T20:44:27Z</updated>
		<content></content>
		<apps:property name='subject' value='test filter'/>
		<apps:property name='shouldMarkAsRead' value='true'/>
		<apps:property name='cannedResponse' value='tag:mail.google.com,2009:cannedResponse:17e0000000000540'/>
		<apps:property name='sizeOperator' value='s_sl'/>
		<apps:property name='sizeUnit' value='s_smb'/>
	</entry>
	<entry>
		<category term='cannedResponse'></category>
		<title>subject</title>
		<id>tag:mail.google.com,2009:cannedResponse:17e0000000000540</id>
		<updated>2022-01-21T20:44:27Z</updated>
		<content type='text'>body
</content>
	</entry>
</feed>
```
</details>

**Comment by mbrt** [comment]
That sounds interesting. There's no official API as far as I can tell, so I wonder how gmailctl could expose filters with canned responses.

**Comment by bkudria** [comment]
@mbrt would creating a filter referencing an inline template (as above) not work? I'm not at all familiar with the APIs you use.

**Comment by mbrt** [comment]
Sorry if it was unclear. From the example you posted, it seems that the XML import / export from Gmail takes canned responses into account. However, the API gmailctl depends upon is the REST one: https://developers.google.com/gmail/api/reference/rest/v1/users.settings.filters. I don't see an equivalent there, so it seems impossible at the moment. Unless I'm missing something.

**Comment by bkudria** [comment]
Gotcha, that makes sense. FWIW, canned responses seem to be a special type of Draft, which does have an API to at least read¹. But it doesn't seem possible to create them²

1: https://stackoverflow.com/questions/56446142/gmail-api-canned-responses
2: https://stackoverflow.com/questions/57102200/create-canned-responses-in-gmail-using-gmail-api#57114820

Feel free to close this issue as you see fit! (and thanks for the rest of gmailctl - it's awesome!)

**Comment by mbrt** [comment]
Oh that looks so ugly! Thanks for the pointers. A part from the limitation on creating drafts, the other issue is that the [users.drafts.list](https://www.googleapis.com/auth/gmail.readonly) API requires at least the `https://www.googleapis.com/auth/gmail.readonly` scope, which is pretty sensitive.

Overall I think it's too early to provide a good experience on this. I'll keep this issue open as the situation may change.
