### ISSUE TITLE
Cant get an OAuth token if my publish status is "In production"

### ISSUE THREAD

**Issue by dabeeeenster** [mbrt/gmailctl#232]
First up thanks for this project! 

I have it working in testing mode but I cant get it working if I publish my app. Tried 3 times, following the instructions as per `gmailctl init`. 

When visiting the authorisation link I get the following from the google oauth page:

```
Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.
Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: urn:ietf:wg:oauth:2.0:oob
```

Not sure if this is a recent change or not. I've followed the `init` instructions to the letter, from what I can tell. Any ideas?

**Comment by mbbroberg** [comment]
This timing is wild @dabeeeenster, I ran into the same experience getting set up today. It does seem like permissions were locked down further since these instructions were written. Is there a way around it? 

If not, is there a way to use this declarative tooling in a "manual mode"? 

I'm thinking I: 

- manually download my existing filters
- import them into gmailctl format 
- export them
- manually delete existing filters & re-upload 

I'd be fine with that level of manual work to get my filters under control. Thanks again for this inspiring project 🌟

**Comment by dabeeeenster** [comment]
@mbbroberg would we not be able to just grab a new token via oAuth if in development mode? 

Amazing how hostile Google is to working with their APIs

**Comment by mbrt** [comment]
I honestly don't know how to make this work reliably long term. I've tweaked the init instructions a number of times already, but it seems Gmail keeps changing their policies. Existing tokens still work (mine does), but I can see how this could affect new users.

I wonder how similar projects are handling this. I would be surprised if this was a change only in Gmail. It probably affects Drive as well.

Re https://github.com/mbrt/gmailctl/issues/232#issuecomment-1060038773: You can use `gmailctl export` to generate the XML to import manually in the Gmail settings.

**Comment by dabeeeenster** [comment]
> 

What about actually going through the process of registering an official app? Has any other OS project done that before?!

**Comment by slackorama** [comment]
FWIW, my token stopped working today. Worked fine last week.

    Response: {
      "error": "invalid_grant",
      "error_description": "Bad Request" 
    }

**Comment by mbbroberg** [comment]
Thank you for looking into this @mbrt. 

> Re [#232 (comment)](https://github.com/mbrt/gmailctl/issues/232#issuecomment-1060038773): You can use `gmailctl export` to generate the XML to import manually in the Gmail settings.

If I'm following correctly, I'm with you on going from gmailctl to XML. I'm looking into going from XML to gmailctl format so I can use gmailctl as a sort of offline declarative editor. I'm hoping to avoid doing it all by hand 😬😅

**Comment by djacu** [comment]
@dabeeeenster Just tried running `gmailctl init` yesterday and ran into the same issue but I couldn't even get it working in testing. Did you do anything in addition to the init setup instructions to get it working.

I just tried creating a new project and starting from scratch this morning and had the same results. I did try putting a couple of my email accounts in the "Test Users" section of the app registration which seems to have fixed it for testing only. It also complained that the email I use for the GCP cannot be a test user but it still seems to have fixed it.

**Comment by dabeeeenster** [comment]
I followed the instructions - have the project set in dev mode and added the email address that I was using the project for. 

Why do Google make this so painful?!

**Comment by dabeeeenster** [comment]
One workaround that would be helpful would be for the `apply` command to open the browser with the token refresh URL if it has expired. I don't run `apply` that often, and refreshing the token only takes 10 seconds or so. If it opened the browser, waited for the auth code and then applied the changes that would be good.

**Comment by mbrt** [comment]
I would prefer if `apply` kept on applying changes and failed if the token has expired. Otherwise several commands may suddenly become interactive. I think a better way to refresh the token is good though, so perhaps there needs to be a command to do that easily. Your workflow could become something like this:

```
gmailctl init --refresh-expired-token && \
gmailctl apply
```

Where the first command doesn't do anything if the token has not expired. Otherwise it prints out the refresh URL and waits.

**Comment by mbrt** [comment]
FTR, the command in https://github.com/mbrt/gmailctl/issues/232#issuecomment-1074077971 doesn't exist yet :)

**Comment by dabeeeenster** [comment]
OH. BOOO 🤣

**Comment by dabeeeenster** [comment]
Yep - using verification and not submitting the app to Google. It works, but my token expires in 7 days.

**Comment by mbrt** [comment]
Yeah using test mode expires in a week and I'm testing that again (I'll need to wait a week). What I'm saying is that setting the app to "production", but without submitting for verification seems to work. in other words I can't reproduce the error in your first comment `Error 400: invalid_request`. Looks like it's not only you though, so I doubt you're doing something wrong.

In any case, I added a flag (called `--refresh-expired`) to make the refresh less painful. Now something like https://github.com/mbrt/gmailctl/issues/232#issuecomment-1074077971 should work, but let me know.

I'll keep this open, but I'm really tired of issues with the authentication changing every 6 months or so. Impossible to test automatically, hard to reproduce, etc.

**Comment by SuperSandro2000** [comment]
I did get the ``redirect_uri: urn:ietf:wg:oauth:2.0:oob`` error and needed to convert my project to testing in https://console.cloud.google.com/apis/credentials/consent and add my email to test users.
Then doing ``gmailctl --refresh-expired`` did the trick. Thank you so much.

**Comment by mbrt** [comment]
Still not gotten around to fixing this.
