### ISSUE TITLE
Redirect URL for auth pointing to localhost

### ISSUE THREAD

**Issue by kjhosein** [mbrt/gmailctl#243]
Hello @mbrt,

Ran across this issue where the URL to get the authorization code looks like: 

> https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=123xyz8gromv5ecgbmmt.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%....

Then I saw [your comment](https://github.com/mbrt/gmailctl/issues/232#issuecomment-1078234435) in an earlier issue that mentions the same thing. 
How did you extract the auth code?
Thanks!

**Comment by durin42** [comment]
It took me a minute to figure it out, but there's a `&code=[^&]+` (regex syntax) segment in the redirect URL, and the part after the `=` there is the code.

**Comment by mbrt** [comment]
Yeah, the auth workflow is quite screwed up at the moment. I still need to figure out what changed and adapt. @durin42 is correct.

**Comment by mbrt** [comment]
Related to #232.
