### ISSUE TITLE
Fresh install with snap cannot succeed due to misconfigured network

### ISSUE THREAD

**Issue by jessedhillon** [mbrt/gmailctl#261]
On the first run of `gmailctl init` on a fresh set of OAuth credentials, the program tries to start a HTTP server, to facilitate an OAuth flow (/cmd/gmailctl/localcred/local_provider.go:139).

On Ubuntu 20.04 after a `sudo snap install gmailctl` I tried to do an init and this was the result:

```
$ gmailctl init
missing or invalid cached token: open /home/jesse/snap/gmailctl/8/.gmailctl/token.json: no such file or directory

Error: starting local server: listen tcp :0: listen: operation not permitted

Note: 
  - gmailctl requires a temporary local HTTP server for the authentication flow.
```

I'm not knowledgeable enough on how to use `snap` to reconfigure an installed package, so I wasn't able to get past this. I installed golang instead.

**Comment by jessedhillon** [comment]
Thanks Gauthier, yes it was a new flow.

**Comment by gjolly** [comment]
Sorry for the spams. I couldn't decide on a commit message :sweat_smile:

**Comment by mbrt** [comment]
Thanks for the super quick fix!
