### ISSUE TITLE
A way to quickly apply changed filters to the existing emails

### ISSUE THREAD

**Issue by samogot** [mbrt/gmailctl#266]
I would be great if there would be a way to execute changed (or all) filters against existing emails. The way I do it now is just go through each filter in settings now and click edit->continue->apply to existing->update. Some of such filter updates can take long time, also it sometimes hard to figure out which filter I should apply after change, because of OR rules decomposition into separate filters.

**Comment by mbrt** [comment]
https://github.com/mbrt/gmailctl#apply-filters-to-existing-emails
