### ISSUE TITLE
Following flow for sorting mails possible?

### ISSUE THREAD

**Issue by DerDominik** [mbrt/gmailctl#361]
Hi there,

at first.. Great project for creating more easy the gmail-filter.

Currently I created my filters manully, but it is very complicated to change something afterwards.
I've several eMail-adressess which forward the mails to my main-gmail-account.

So I want to switch to gmailctl, but I'm asking myself, if the following mail flow is possible.

1. Manual Spam-Check (sometimes they are detected by the gmail-spamfilter) and set NoSpam
2. Check for the Mail-Sender (depending on the Mail-Sender only one specific label is set)
3. Check for the Mail-To (depending on the Mail-To only one specific label is set)
4. If no possibility from above, then set another specific label

For a better view I created a flowchart

![mailflow](https://github.com/mbrt/gmailctl/assets/16927324/3ac3e6ab-297f-43fb-874c-542c494aebdb)

So here's my starting jsonnet, but afterwards the created filter looks very weird and I don't think, that it is working.

```
local lib = import 'gmailctl.libsonnet';

local me_mail1 = 'mail1@gmx.de';
local me_mail2 = 'mail2@gmx.de';

{
  version: 'v1alpha3',
  author: { name: 'xxx', email: me_mail4 },

  rules: [
    {
      filter: { from: "blablabla1@test.org OR blabla2@aol.com" },
      actions: { markSpam: false },
    },
  ]

  + lib.chainFilters([
    {
      filter: { from: "Amazon" },
      actions: { archive: true, markSpam: false, labels: [ "Amazon" ] },
    },
    {
      filter: { from: "Paypal" },
      actions: { archive: true, markSpam: false, labels: [ "Paypal" ] },
    },
    {
      filter: { to: me_mail1 },
      actions: { archive: true, markSpam: false, labels: [ "(1) Mail1" ] },
    },
    {
      filter: { to: me_mail2 },
      actions: { archive: true, markSpam: false, labels: [ "(2) Mail2" ] },
    },
  ]),
}
```

So, it is in general possible to realize my mail-filter-flow?
And maybe someone has an example

Thanks for your help,
Dominik

**Comment by mbrt** [comment]
From a cursory glance this looks OK.

To simplify, you should probably reduce `chainFilters` to a minimum. There's no need to chain rules if there's no overlap (i.e. no `if-else-if-else`). For example `from:amazon` and `from:paypal` will never be true at the same time. This means that you can just have them as separate rules and simplify the resulting filters:

```
  rules: [
    {
      filter: { from: "blablabla1@test.org OR blabla2@aol.com" },
      actions: { markSpam: false },
    },
    {
      filter: { from: "Amazon" },
      actions: { archive: true, markSpam: false, labels: [ "Amazon" ] },
    },
    {
      filter: { from: "Paypal" },
      actions: { archive: true, markSpam: false, labels: [ "Paypal" ] },
    },
  ]

  + lib.chainFilters([
    {
      filter: { to: me_mail1 },
      actions: { archive: true, markSpam: false, labels: [ "(1) Mail1" ] },
    },
    {
      filter: { to: me_mail2 },
      actions: { archive: true, markSpam: false, labels: [ "(2) Mail2" ] },
    },
  ]),
}
```

Perhaps this is true also for other rules you're chaining. In practice `chainFilters` are necessary only in rare cases. I personally never really had to use them.
