### ISSUE TITLE
Could libsonnet helper files be situated next to the tmp file for `gmailctl edit` to avoid import path errors?

### ISSUE THREAD

**Issue by dbarnett** [mbrt/gmailctl#378]
With the way `gmailctl edit` opens an editor on a tmp file, any smart editors/plugins trying to analyze the jsonnet file will tend to get tripped up on libsonnet import paths:

![libsonnet import path error in VS Code](https://github.com/mbrt/gmailctl/assets/65244/10f66278-a9c8-4b00-a6ad-4652cf778182)

Would it be reasonable for `gmailctl edit` to copy or symlink related files over into a tmp directory so those kinds of things in the editor can work more seamlessly?

So concretely here, instead of copying my ~/.gmailctl/config.jsonnet file to /tmp/gmailctl-645862603.jsonnet and opening that in an editor, it could have created a directory /tmp/gmailctl-645862603/ and set it up like this before spawning an editor on /tmp/gmailctl-645862603/config.jsonnet:
  * copy config.jsonnet
  * symlink *.libsonnet (and potentially other jsonnet or config files that could be relevant)

**Comment by dbarnett** [comment]
FWIW when I say "potentially other jsonnet or config files", there are some credentials.json and token.json files that might be better _not_ to copy over. I do have a weird _schema.json file there that might someday be useful to clone over too so I could reference it [in a schema directive like this](https://github.com/dbarnett/dotfiles/blob/261ad41437057a930ca2fafc65e5d29c5ad81445/.config/jj/config.toml%23%23template%2Ce.toml#L1C24-L1C24) but I haven't figured out a way to get that kind of thing working with jsonnet.

**Comment by mbrt** [comment]
Ah yeah that's something we should fix.

Another idea as well. What about also using the same directory where the config is sitting? This would avoid the symlinks at least. Only if this fails we could fall back to the regular temp directory (old behavior).

**Comment by dbarnett** [comment]
> What about also using the same directory where the config is sitting?

Oh, good point! That'd work great for me.

**Comment by dbarnett** [comment]
Excellent, thanks! I tested it out locally and it works great!
