### ISSUE TITLE
automatic quoting of addresses with plus sign should not quote addresses that are already quoted

### ISSUE THREAD

**Issue by leinaddm** [mbrt/gmailctl#383]
I have a bunch of filters that contain addresses with plus signs, they used to be configured like the following in my config: 

```
from: "'foo+bar'"
```

After a recent gmailctl update syncing shows the following diffs:

```
- from: "foo+bar"
+ from: ""foo+bar""
```

Pushing that diff would break the filter. I think the issue is likely around https://github.com/mbrt/gmailctl/blob/cca5a22ea640c9cca7fbfeaf891fa98829e08c79/internal/engine/filter/convert.go#L255
that automatically quotes addresses with plus signs unless they are a full email addresses. The code should likely not quote if the address is already quoted, but that code is from a couple of years ago and I just noticed the issue a couple of weeks ago (but maybe the package I am using was old, not sure as it came from an internal package repository).

Any idea whether the issue could be somewhere else ?
Thank you

**Comment by mbrt** [comment]
Hey Daniel, there was an attempt at fixing this in #66, which also caused issues. The idea was to error out when quotes would have been doubled.

At this point, I'm afraid to add any magic, as maybe we're missing more cases where it breaks.

To start, I'm assuming you can fix your config by removing your double quotes, correct?

For the long term, do you think it would be helpful if quoting happened only when not-already-quoted?

**Comment by leinaddm** [comment]
sorry for the late reply, yes I was able to fix my filters by just removing the extra quotes and that produced no diffs. 

As for long term, I think not auto-adding quotes if they are already there would be a good compromise.
