### ISSUE TITLE
Gmail labels are not refreshed when 'continue editing' is chosen

### ISSUE THREAD

**Issue by gabormay** [mbrt/gmailctl#40]
Repro:
1. gmailctl edit
2. Add a new rule using a label that does not exist
-> edit fails, user presented with option 'Do you want to continue editing?'
3. Choose 'y'
4. Add the label in gmail (leaving the editor open)
5. Try to go ahead with the edit
-> Still results in the same error (Label does not exist)

Expected: edit should go through once the label is added

Note: if you choose to abort the editing, the changes you made to the config are lost, or at least there's no obvious way to recover them

**Comment by mbrt** [comment]
Good catch. Labels should be refreshed before retrying.
