### ISSUE TITLE
supporting the "Indef" label

### ISSUE THREAD

**Issue by aktau** [mbrt/gmailctl#414]
The "Indef" label is a pre-existing label that I can attach to mails. But I can't create a rule applying it to certain mails.

If I try to add a rule without mentioning "Indef" in the labels list, I get:

```
Applying the changes...
Error: creating filters: exporting filter #0: in export action: label "Indef" not found
```

If I try explicitly mentioning the label in the labels list:

```
Applying the changes...
Error: creating labels: creating label "Indef": googleapi: Error 409: Label name exists or conflicts
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.DebugInfo",
    "detail": "Label name exists or conflicts",
    "stackEntries": [
```

I wonder if (a) there exist more of these special labels and (b) if it's worth supporting them. Currently I've specified a manual rule. gmailctl seems to leave it alone. It's fine as a workaround, though it'd be nicer to make this configuration explicit in configuration.

Thanks for the great tool.

**Comment by mbrt** [comment]
Hey Nicolas,

IIRC the `Indef` label is special and only internal in Google. Gmail APIs blatantly ignore it and filter it out in both labels and filters queries. This means that any filter mentioning that label will not be visible to gmailctl (or any other API based tool).

There should be some internal documentation on this as well.
