### ISSUE TITLE
Include an option to continue editing instead of applying filters

### ISSUE THREAD

**Issue by tbodt** [mbrt/gmailctl#43]
I just spent about an hour writing a fairly complicated set of rules, then saved the file and checked the diff and it didn't look quite right. So I typed `n` and re-ran `gmailctl edit` and was quite shocked to see all my work had disappeared...

It would be nice if there was another option other than y/n: perhaps `e` to re-open the file. Also an indication that `n` will discard your changes.

**Comment by mbrt** [comment]
Sorry to hear that. The edited version is in `/tmp`. I checked and the location is not printed out, so this I can improve.

I think you're right though, editing, checking and wanting to come back seems to be an important enough use case. I'll see what I can do to make it as less confusing as possible. Perhaps the default when selecting `n` should be to go back editing, and I should add an `abort` option. What do you think?
