### ISSUE TITLE
Can I filter emails sent to a list by a specific person?

### ISSUE THREAD

**Issue by amir-mehler** [mbrt/gmailctl#45]
For example: Can I filter an email that looks like this, but only when it's from this specific some-one.

    from: 'Some, One' via list-name <list-name@gmail.com>
    reply-to: "Some, One" <some-one@gmail.com>
    to: "list-name (list-name@gmail.com)" <list-name@gmail.com>
    mailing-list: list-name@gmail.com

**Comment by mbrt** [comment]
Yes. Since you want both things to be true, you need an AND:

```jsonnet
filter: {
  and: [
    { from: 'some-one@gmail.com' },
    { list: 'list-name@gmail.com' },
  ],
},
actions: ...
```

**Comment by amir-mehler** [comment]
But I don't have the "from" address. The person emailed the list and I'm seeing the email as:
from: list-name
to: list-name

**Comment by mbrt** [comment]
Ah apologies, I misread the issue.

Try by using the name instead of the email:

```jsonnet
filter: {
  and: [
    { from: 'Some One' },
    { list: 'list-name@gmail.com' },
  ],
},
actions: ...
```

**Comment by amir-mehler** [comment]
Ok after some testing both of these options work for emails that reach the same mailing list but require different actions.

    // Setting the 'from' to the name as it appears in the UI
    local nameRule = {
      filter: {
        and: [
          { from: 'Someones, Name' },
          { list: 'some-list' },
        ]
      },
      actions: {
        markImportant: true,
      },
    };

Also this works; Query the 'reply-to' field

    local anotherRule = {
      filter: { query: 'replyto: donotreply@wordpress.com' },
      actions: { labels: ['label'], archive: true }
    };
