### ISSUE TITLE
askYN methods default 'N' does not behave as expected

### ISSUE THREAD

**Issue by amir-mehler** [mbrt/gmailctl#47]
When (for example) you run `gmailctl apply` you are prompted with

    Do you want to apply them? [y/N]:

The Linux style of `[y/N]` suggests that the default behaviour when just hitting the Return key will be 'N' and nothing will happen. But currently, this flow will get you stuck.

To reproduce, make a change, run `gmailctl apply` and when prompted just hit return.

Tested on Mac with iTerm

I suspect this originates in the `askYN` method that uses `fmt.Scanln` that gives an error if you just hit return.

I will submit a PR with an alternative for `fmt.Scanln` using bufio `ReadString`

**Comment by mbrt** [comment]
Thanks for the report (and the patch).
