### ISSUE TITLE
Add lint command

### ISSUE THREAD

**Issue by studgeek** [mbrt/gmailctl#51]
A simple `lint` command would be nice for just checking to see if the file is properly formed. Currently I use `debug`, but it would be nice to check the file without all that output in the terminal.

**Comment by mbrt** [comment]
Yeah, that makes sense. It can be done pretty easily, although the error messages when parsing fails are not incredibly useful :)

**Comment by mbrt** [comment]
This is now handled by the `gmailctl test` command, which does this and a bit more if you happen to include tests in your config. I believe this can be closed.

Feel free to reopen if you disagree.
