### ISSUE TITLE
document required scopes for gmailctl

### ISSUE THREAD

**Issue by slippycheeze** [mbrt/gmailctl#55]
gmailctl requires only one specific scope to function:
```
https://www.googleapis.com/auth/gmail.settings.basic
```

It'd be nice to document that, rather than advising to create what amounts to read-write access to *everything* during project setup.  (Also, best practice, of course.)

If you do what I asked in #54 then you would also need
```
https://www.googleapis.com/auth/gmail.labels
```

You can find the specific scopes by hitting the reference pages, such as:
https://developers.google.com/gmail/api/v1/reference/users/labels/create#auth

**Comment by mbrt** [comment]
Thanks, I missed that part. Note that however, independently on how you created the project, gmailctl specifically scopes the API to the minimal permissions. See [pkg/api/auth.go](https://github.com/mbrt/gmailctl/blob/master/pkg/api/auth.go#L83). Limiting this also at the project level seems like a good idea anyway.

**Comment by slippycheeze** [comment]
In my case it came from the discovery that the recommended "user data" wizard version included a scope in the project auth page that ran into a security policy that'd require review, while these settings only are fine without.  

I'm not sure this'll be an issue for anyone outside large organizations with strict security policies, but even for the average "home" user it means that a leaked token is only able to be used for these changes, while the wizard version could be used to read all email content, or mutate it.

So ... protects users against their own mistakes, basically.
