### ISSUE TITLE
Add "forward" action (to forward emails)

### ISSUE THREAD

**Issue by slix** [mbrt/gmailctl#56]
"Forward it to: Choose an address.." from Gmail's filter creation is missing as an Action option in gmailctl.

The [Gmail API](https://developers.google.com/gmail/api/v1/reference/users/settings/filters) supports it as `action.forward`. The parameter is a string containing the forwarding email. I confirmed this with the API explorer.

However, forward is different because it's not a pseudo-label like gmailctl's other actions.

`user.settings.filters.create` returns an error if the forwarding address is not set up on the user's account:

```json
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "failedPrecondition",
    "message": "Unrecognized forwarding address"
   }
  ],
  "code": 400,
  "message": "Unrecognized forwarding address"
 }
}
```

The same error happens for malformed input, like `@` or `[][]`. **The empty string succeeds as if `forward` was absent.**

Should we care about the case where a user wants one filter to forward to multiple email addresses? It's probably rare, and I'm not sure how Gmail would react to the duplicate queries with different forwarding addresses.

I'm blocked from using gmailctl for my personal email because I have 3 filters that forward my email. I forward my award point statements to AwardWallet (so that it doesn't have permissions to read my entire mailbox).

I looked at the code a bit, and I may try implementing this in the next week or so.

**Comment by mbrt** [comment]
Makes sense. I believe (but I'd have to check) that to be able to set that field you need to get higher privileges for the Gmail account access. If that's not the case this can be added easily. Otherwise people will have to re-authorize their API access + have the possibility to opt-out, since this is a sensitive setting that could blow your privacy.

Let me know if you have the answer to this question, plus if you want to work on that. This will also need a version bump of the config.

**Comment by slix** [comment]
Working on it. Finished the code, working on tests.

Gmail allows unlimited filters but only 20 filters that forward. Not sure whether that's a problem.

**Comment by mbrt** [comment]
The config file doesn't need to change anymore, since the new version includes all this feature needs.

**Comment by sejmann** [comment]
Any chance this might get some traction soon, @slix / @mbrt?  It looks so tantalizingly close to being finished.  I'm another user of forwards, and I think that's that last outstanding feature I personally need. =)

**Comment by mbrt** [comment]
This is not a complicated change, I just need to get to it.
Contributions are also welcome, in case I'm too slow :)

**Comment by slix** [comment]
Sorry, I haven't gotten to the code review feedback. If you build from my
GitHub fork, it should work fine. I used it locally. I just haven't added
the tests and stuff yet.
