### ISSUE TITLE
Is it possible to control the order of filters?

### ISSUE THREAD

**Issue by DannyDeLoach** [mbrt/gmailctl#62]
gmailctl is a wonderful tool! I've been searching for something like this for a long time. Thank you for creating it.

I created a config file with about 20 or so filters. When I apply the config fild to my Gmail account, the filters do not remain in the order I have them in the config file. The order in the Gmail UI seems to be random.

I don't _need_ the filters to be in order. My concern is not at all related to the sequence in which the filters are applied. I would like the filters in the Gmail UI to reflect the order of the filters in my config file, because that would help me manage them better. For example, if something is going wrong with a filter, I would be able to more quickly and easily find it in the Gmail UI, if the filters were in my preferred order.

Thanks, again, for creating this great tool.

[P.S. I apologize for not adding a tag to this post. I intended to label it as a question. I see on the right side it says, 'Labels: None yet', but I don't see how to give the post a label.]

**Comment by mbrt** [comment]
This is unfortunately not possible. Gmail doesn't allow the order to be specified and by default it seems that new filters get at the bottom. Gmailctl provides quick editing by deleting and re-creating only the filters that you change since the last edit. This naturally shifts the order around. The only way to force an ordering would be to delete all the filters and re-upload all of them, but that's going to be quite slow.

I wouldn't be keen in adding this functionality, since the end result would be a considerably slowed down edit workflow.

**Comment by DannyDeLoach** [comment]
Thanks for the explanation. It's unfortunate Gmail doesn't respect the order in which filters are uploaded, when they are all uploaded at the same time. I deleted all of my filters in Gmail. Then, I re-uploaded them all again. They appeared in the Gmail UI in random order. So, as you've said, it appears there is no easy way to control the order of filters in Gmail.

I found a workaround. I deleted all my filters in Gmail. Then, I edited my config file to comment out all but the first filter rule. Then, I applied the config file to Gmail. Then, I edited the config file again, this time un-commenting the second filter rule. Then, I applied the config file again. I followed this sequence, until I had all my filters uploaded to Gmail. The end result was all of the filters in my desired order within the Gmail UI.

I realize this workaround is not great. For one, it's tedious. Second, when I edit any of my filter rules in the config file in the future, then the newly edited filter will appear at the bottom of the filter list in Gmail.

I'll mark this issue as closed. I feel you've done all you can do to address this issue in a feasible way. Again, it's just too bad Gmail doesn't respect the upload order of filters.

Thanks, again, for this great tool.
