### ISSUE TITLE
Is there a way to set a variable with both "to" and "from" email addresses?

### ISSUE THREAD

**Issue by DannyDeLoach** [mbrt/gmailctl#63]
As I said in a previous post, thank you for this great tool.

I have a set of co-workers, and I have a filter that applies a label to messages _received from_ these co-workers or _sent to_ these co-workers. The list of co-workers includes about twenty people.

To setup this filter in the config file, I created two variables. The first variable looks like this:

local fromCoworkers = {
  or: [
    { from: 'person1@acme.org'},
    { from: 'person2@acme.org'},
    { from: 'person3@acme.org'},
     ...
    { from: 'person20@acme.org'},
  ],
};

The second variable looks like this:

local toCoworkers = {
  or: [
    { to: 'person1@acme.org'},
    { to: 'person2@acme.org'},
    { to: 'person3@acme.org'},
     ...
    { to: 'person20@acme.org'},
  ],
};

And the filter rule looks like this:

    {
      filter: {
        or: [
          fromCoworkers,
          toCoworkers,          
        ],
      },
      actions: {
        labels: [
          "Coworkers"
        ]
      }
    },

This works, but I have to maintain two versions of the same list. I have to list all twenty email addresses in the fromCoworkers variable and then the same set of email addresses in the toCoworkers variable.

Is there a way to do this, so that I only have to maintain one list?

Thanks.

[As with my previous post, I intended to label this as a question. I just read the Github help files about applying labels to issues. It looks like only the owner of a project can apply labels. Anyway, I hope I'm not doing this wrong by not applying a label.]

**Comment by mbrt** [comment]
This is possible thanks to Jsonnet super-powers. You could create a list of coworkers, and a `from` and `to` functions that take a list and do the required transformation. Example:

```
local to(ls) = {
  or: [{ to: x } for x in ls],
};
local from(ls) = ...

{
  filter: {
    or: [
      from(coworkers),
      to(coworkers),
    ],
  }
```

You could go even a step further and define a `senderOrRecipients()` function.

What seems to me easier though is to just filter for *@acme.org and perhaps exclude some addresses from there, instead of maintaining a very long list of coworkers.

**Comment by DannyDeLoach** [comment]
I used your first suggested method. It worked great! Thanks!
