### ISSUE TITLE
jsonnet helper for filter creation

### ISSUE THREAD

**Issue by blackjid** [mbrt/gmailctl#67]
I've been thinking about adding some helper functions to the gmailctl.libsonnet library.

In particular, I'm looking on a way to create valid structured filters using the logic operators. May be something that could be used like this,

```
local gmailctl = import 'gmailctl.libsonnet';
local Filter = gmailctl.Filter;

Filter.new()
=>
{}

Filter.new().and({to: "me@email.com"}).values()
=>
{
  and: [{to: "me@email.com"}]
}
```

The idea would be to be able to use method chaining to build and reuse filters. You could do something like

```
local to_me = Filter
				.new()
				.and({to: "me@email.com"});

local chained_filter = Filter
						.new()
						.and({subject: "special email"})
						.or(to_me);

chained_filter.values();
=>
{
	and: [{subject: "special email"],
	or: [{ and: [{to: "me@email.com"}]]
}
```

I'm a noob in jsonnet, I've been trying to implement something like this with some success. I'd love to know your thoughts on the idea, implementation, and d actual syntaxis.

**Comment by mbrt** [comment]
I don't know how many people would like to see something like this in the common library, but I know what you can do to get there, if you want:

1. You write a proposal with goals and some implementation details.
1. Minimal working implementation.
1. Add a decently documented version to the repo as a contribution (something people can download separately).
1. Make it available in the standard library if adoption justifies it.

I think that especially 1. is important. What are you trying to achieve with this? Less typing? More clarity? In which way would this be advantageous? What is the disadvantage of not having this?

Point 4. also depends in how much other people like this.

Disclaimer: I'm not a Jsonnet guru either. One question that comes to mind however is: how do you see nested filters working? How would something like `and(or(not(A), B), C)` be represented with your helpers?

As an aside,  I was thinking to add some shortcuts that I saw people using in the wild quite a few times. Example:

```jsonnet
local lists(ls) = {
  or: [{ list: x } for x in ls],
};

// usage
{
  filter: lists(['foo@bar.com', 'baz@baz.com']),
  actions: { archive: true },
}
```

Thanks for your contributions!

**Comment by blackjid** [comment]
Well, I think the bot made me look at this again.. Sorry never answered and thank you for the detailed response.
I think you got me on the first questions so if I ever get back to improve my gmailctl definitions I might get back to analyze this idea...
