### ISSUE TITLE
diff not showing differences

### ISSUE THREAD

**Issue by leinaddm** [mbrt/gmailctl#69]
I downloaded my filters from gmail and the diff command shows no diffs.
However when I look in gmail I have filters like the following:

```
Matches: list:foo.bar.com -{(to:email@address.com)}
Do this: Skip Inbox

Matches: list:foo.bar.com
Do this: Apply label "list"
```

The downloaded filters look like:

```
    {
      filter: {
        query: "list:foo.bar.com"
      },
      actions: {
        archive: true
      }
    },
    {
      filter: {
        query: "list:foo.bar.com"
      },
      actions: {
        labels: [
          "list"
        ]
      }
    },
```

and seem to have lost the part excluding emails sent directly to me.

Am I misunderstanding how the config is supposed to work?

**Comment by mbrt** [comment]
Is this all your config? I tried this exact thing and saw no problems. It's also strange that the diff tells you there's no change if the config is clearly different. Could you double check with a minimal example that reproduces the problem?

**Comment by leinaddm** [comment]
no, the config is huge. I'll try to reproduce it with a smaller config, but I'm traveling until the end of Oct, I'll report back once I return.

**Comment by leinaddm** [comment]
Uploading the attached filters to a gmail account and then downloading them with "gmailctl download" reproduces the issue above.
I think the issue might be in the fact that the -{(email@address.com)} part is returned in a separate tag in the xml. It might do the same thing in the api gmailctl is using (?)

[f.zip](https://github.com/mbrt/gmailctl/files/3665289/f.zip)

**Comment by mbrt** [comment]
Sorry for the delay, and thanks for the snippet, I can reproduce it on my side.

The issue is indeed because in your filters you are using the "doesn't have" part of the filter. From the APIs it looks like this:

```json
  {
   "id": "XYZ",
   "criteria": {
    "query": "list:bla.bla.bla",
    "negatedQuery": "(to:foo@bar.com)"
   },
   "action": {
    "removeLabelIds": [
     "INBOX"
    ]
   }
  }
```

And this is not correctly handled by the `download` command.
