### ISSUE TITLE
Consider adding installation prerequisites

### ISSUE THREAD

**Issue by matkoniecz** [mbrt/gmailctl#8]
I suspect that my go version is outdated, but maybe something else went wrong (I am trying to run go program for the first time in my life).

```
mateusz@grisznak:~/Desktop/tmp$ go install github.com/mbrt/gmailctl/cmd/gmailctl
can't load package: package github.com/mbrt/gmailctl/cmd/gmailctl: cannot find package "github.com/mbrt/gmailctl/cmd/gmailctl" in any of:
	/usr/lib/go-1.6/src/github.com/mbrt/gmailctl/cmd/gmailctl (from $GOROOT)
	($GOPATH not set)
mateusz@grisznak:~/Desktop/tmp$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by matkoniecz** [comment]
From looking at travis it seems to be testing go at `stable` and `tip`, currently meaning `1.11.1` and `devel +a2381f5966`.

Should I assume that only latest stable version mentioned at https://golang.org/doc/devel/release.html is supported?

**Comment by mbrt** [comment]
You need to first `go get` the package this way:

```
go get github.com/mbrt/gmailctl/cmd/gmailctl
go install github.com/mbrt/gmailctl/cmd/gmailctl
```

Also make sure that the install path is in your `$PATH`.

I don't know exactly what's the minimum version that works with this package, but 1.6 should be OK.

**Comment by matkoniecz** [comment]
I think that explicit

```
go get github.com/mbrt/gmailctl/cmd/gmailctl
```

would be helpful for `go` newbies - especially as `go get` has some useful complaints like complaining about unset `$GOPATH`. I plan to make PR adding it to instructions, hopefully it is OK.

------

Apparently, according to https://github.com/prometheus/collectd_exporter/issues/37#issuecomment-252722782 1.7 go is minimum

```
mateusz@grisznak:~/Desktop/tmp$ echo $GOPATH
/home/mateusz/Documents/install/gopath_target
mateusz@grisznak:~/Desktop/tmp$ go get github.com/mbrt/gmailctl/cmd/gmailctl
package context: unrecognized import path "context" (import path does not begin with hostname)
```

and later

```
mateusz@grisznak:~/Desktop/tmp$ go install github.com/mbrt/gmailctl/cmd/gmailctl
../../Documents/install/gopath_target/src/github.com/mbrt/gmailctl/cmd/gmailctl/cmd/init_cmd.go:4:2: cannot find package "context" in any of:
	/home/mateusz/Documents/install/gopath_target/src/github.com/mbrt/gmailctl/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/mateusz/Documents/install/gopath_target/src/context (from $GOPATH)
```

**Comment by mbrt** [comment]
You are right, I did that already when I saw this issue (See updated README). I suspect the [gmail APIs](https://developers.google.com/gmail/api/quickstart/go) want new releases of Go, although they don't specify which one.

**Comment by matkoniecz** [comment]
>  I did that already when I saw this issue (See updated README)

I believe that it fixes this issue...

Thanks!
