### ISSUE TITLE
Test failures should show actions diffs

### ISSUE THREAD

**Issue by lutzky** [mbrt/gmailctl#81]
Sample error message:

```
config tests failed: test 'stuff' failed: message #0 is going to get unexpected actions: {"archive":true,"labels":["stuff"]}
```

The test was configured to just check for `labels: ["stuff"]`. A test failure would look nicer like so:

```
config tests failed: test 'stuff' failed: message #0 is going to get unexpected actions, -want +got:
 {
+  "archive": true,
   "labels":["stuff"]
 }
```

This should be easy using https://github.com/google/go-cmp.

**Comment by lutzky** [comment]
As a naive example, doing this in `ExecTest`:

```go
diff := cmp.Diff(expected, Actions(t.Actions))
return fmt.Errorf("message #%d is going to get unexpected actions: %s\nDiff -want +got:\n%s", i, reporting.Prettify(expected, true), diff)
```

Yields this:

```
config tests failed: test 'test1' failed: message #0 is going to get unexpected actions: {"archive":true,"labels":["news"]}
Diff -want +got:
  cfgtest.Actions(
-       {Archive: true, Labels: []string{"news"}},
+       {Archive: true},
  )
```

Which is nice, but doesn't actually show that `Archive: true` is shared. Also, it formats everything in Go-types, so we have both unsightly `[]string{}`, and `Archive` instead of `"archive"`. :thinking:

**Comment by lutzky** [comment]
Ah, but doing the diff like so instead:

```go
diff := cmp.Diff(cfg.Actions(expected), t.Actions))
```

...yields this diff:

```
Diff -want +got:
  v1alpha3.Actions{
        ... // 5 identical fields
        MarkImportant: nil,
        Category:      "",
-       Labels:        []string{"news"},
+       Labels:        nil,
        Forward:       "",
  }
```

...which is closer to what I have in mind, but still quite messy. One option is converting both sides to JSON (which `reporting.Prettify` appears to do) and using some JSON comparison library to show the diff.

**Comment by mbrt** [comment]
I would use something like this:

```
diff := cmp.Diff(reporting.Prettify(expected, false), reporting.Prettify(got, false))
```

Where `Prettify` is this: https://github.com/mbrt/gmailctl/blob/master/pkg/reporting/err.go#L9. It should show up similarly to what you expect.
