### ISSUE TITLE
write filter that runs in order

### ISSUE THREAD

**Issue by vtolstov** [mbrt/gmailctl#90]
Thank you for wonderful project! I have more then 70 filters in gmail and using such tool is really helpful.
My current problem that i have some filters for single "to" address that can fills to multiple labels , does it possible to write something that if filter matches - it labeled and stop processing other filters?
This is really can helps in situations when you need to have big "not" stuff inside many filters. (i'm don't like to see one email in multiple labels)

**Comment by mbrt** [comment]
You can simulate that behavior by using [chain filtering](https://github.com/mbrt/gmailctl#chain-filtering). Unfortunately Gmail doesn't support this natively, so this function generates the required "not" expressions for you.

Let me know if this fixes your problem.

**Comment by vtolstov** [comment]
yes, it looks good!
