### ISSUE TITLE
Clearer or updated instructions

### ISSUE THREAD

**Issue by tcurdt** [mbrt/gmailctl#91]
```
1. Create a new project if you don't have one
1. Go to 'Enable API and services' and select Gmail
2. Go to credentials and create a new one, by selecting 'Help me choose'
   2a. Select the Gmail API
   2b. Select 'Other UI'
   2c. Access 'User data'.
3. Go to 'OAuth constent screen' and update 'Scopes for Google API', by
   adding:
     * https://www.googleapis.com/auth/gmail.labels
     * https://www.googleapis.com/auth/gmail.metadata
     * https://www.googleapis.com/auth/gmail.settings.basic
4. IMPORTANT: you don't need to submit your changes for verification, as
   you're not creating a public App
5. Download the credentials file into '/Users/tcurdt/.gmailctl/credentials.json'
   and execute the 'init' command again.
```

This is not covered:

![Screen Shot 2020-03-29 at 15 43 15](https://user-images.githubusercontent.com/13697/77850631-1ce50d00-71d4-11ea-8945-3dfc0a93bcae.png)

After step 4 it says

![Screen Shot 2020-03-29 at 15 40 40](https://user-images.githubusercontent.com/13697/77850574-c972bf00-71d3-11ea-9163-37f408d10eee.png)

and there is no way to "Save" without adding more information.

**Comment by shoenig** [comment]
To "save" from there, I found you just need to fill out the app name box. 

However, I'm them stuck in the next step, "Download the credentials file" which doesn't seem to be available.

**Comment by tcurdt** [comment]
Got it working, too! Thanks.
But I leave the issue open as the instructions should be updated/improved.

**Comment by mbrt** [comment]
Thanks! I will update the instructions with the suggestions.
