### ISSUE TITLE
Diff can be a bit unclear

### ISSUE THREAD

**Issue by dcormier** [mbrt/gmailctl#96]
I have this as a filter in `config.jsonnet`:

```jsonnet
      filter: {
        and: [
          {
            from: '@paypal.com',
          },
          {
            or: [
              {
                subject: 'Receipt for *',
                isEscaped: true,
              },
              {
                subject: 'authorized a payment',
                isEscaped: true,
              },
            ],
          },
        ],
      },
```

When I run `gmailctl diff`, that `or` branch is shown as:

```
+    subject: {Receipt for * authorized a payment}
```

It makes it look like the subject `Receipt for * authorized a payment` is being matched, rather than `Receipt for *` or `authorized a payment`.

**Comment by mbrt** [comment]
What you see is correct, because you are using `isEscaped: true`, which doesn't add quotes or does escaping for you. Please try to drop that part and you should see the result you expect.

**Comment by dcormier** [comment]
Hm. Actually, it seems that the diff was not unclear. It did exactly as it said it was going to. This is what was created in GMail:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/216265/78452646-601f0000-765a-11ea-9fef-0a85e05d484e.png">

That's not at all what I expected.

**Comment by mbrt** [comment]
Yes, see my comment above. Remove both `isEscaped: true` and it will add quotes appropriately.

The marker is added by the `download` command to filters where there's no clear mapping to expressions in gmailctl. As you change an imported filter, you should first convert the expression into one that doesn't require the `isEscaped: true` marker.

In your case it's easy as you don't use operators inside those strings, but consider e.g:

```jsonnet
{
  from: "{foo bar baz}",
  isEscaped: true,
}
```

This should be converted into:

```
{
  or: [
    {from: "foo"},
    {from: "bar"},
    {from: "baz"},
  ],
}
```

Does that make sense?

**Comment by dcormier** [comment]
OK, that seemed to work.

Is it worthwhile to report filters that are imported with `isEscaped:true` so this can be improved?

**Comment by mbrt** [comment]
I have added some clarifications in 5fcb4789a98a29e0aeffdc3f0d8a5d6e858f101e. Do you think it's enough?

**Comment by dcormier** [comment]
I think so.

**Comment by mbrt** [comment]
Great. Closing this then.
