### ISSUE TITLE
download command doesn't support filters with HasAttachment

### ISSUE THREAD

**Issue by klauern** [mbrt/gmailctl#97]
When running the `download` subcommand, it fails with 

```
$ gmailctl download
error importing filter #0: empty criteria
```

In looking at it, my first filter is one that labels things with File Attachments:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/4735/78503014-ad1dd780-7729-11ea-95ce-73137c47dba1.png">

As that has no criteria around those defaulted or assumed filters, it fails, even though it's something you can create a filter around.

It would be nice to be able to have it skip over these if they aren't currently downloadable, or to add support for other criteria fields.

**Comment by klauern** [comment]
To add to it, here's the filter in question

<img width="423" alt="image" src="https://user-images.githubusercontent.com/4735/78503064-f2420980-7729-11ea-907b-3b71291d18b1.png">

**Comment by klauern** [comment]
and the actual filter from the API:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/4735/78503204-c96e4400-772a-11ea-850f-4ed969ac5ffe.png">

**Comment by mbrt** [comment]
Thanks for reporting! `HasAttachment` is not supported indeed. Two problems here:

* Unsupported filters should be skipped (although syncing afterwards will delete them).
* HasAttachment support should be added.
